CREATE TABLE users (
id BIGSERIAL PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL);

CREATE TABLE categories(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE,
description VARCHAR(255));

CREATE TABLE products(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description VARCHAR(255),
price NUMERIC(10,2) NOT NULL,
stock INTEGER NOT NULL DEFAULT 0,
category_id BIGINT NOT NULL REFERENCES categories(id));